"""empty message

Revision ID: e01889477551
Revises: b8836366bc46
Create Date: 2025-03-24 12:43:43.794756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01889477551'
down_revision = 'b8836366bc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliations', sa.String(length=100), nullable=False))
        batch_op.drop_column('Affiliations')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliations', sa.String(length=100), nullable=False))
        batch_op.drop_column('Affiliations')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliations', sa.String(length=100), nullable=False))
        batch_op.drop_column('Affiliations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Affiliations', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('affiliations')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Affiliations', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('affiliations')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Affiliations', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('affiliations')

    # ### end Alembic commands ###
